version: '3.8'

services:
  biolink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passabot-biolink
    restart: always
    networks:
      - passabot_network
networks:
  passabot_network:
    external: true
