name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - main

env:
  GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          printf '%s\n' "$GCP_PRIVATE_KEY" > private-key.pem
          chmod 600 private-key.pem
        env:
          GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}

      - name: Git Pull e Docker compose
        run: |
          ssh_user=root
          ip_address=34.68.95.239
          branch=main

          ssh -o StrictHostKeyChecking=no -i private-key.pem $ssh_user@$ip_address "
            cd github/biolink
            git pull origin $branch
            docker compose up --build -d
            "

            
