name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - main
      - dev

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  CGP_PRIVATE_KEY: ${{ secrets.CGP_PRIVATE_KEY }}
  CGP_PRIVATE_KEY_DEV: ${{ secrets.CGP_PRIVATE_KEY_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            printf '%s\n' "$CGP_PRIVATE_KEY_DEV" > private-key.pem
          else
            printf '%s\n' "$CGP_PRIVATE_KEY" > private-key.pem
          fi
          chmod 600 private-key.pem
        env:
          CGP_PRIVATE_KEY: ${{ secrets.CGP_PRIVATE_KEY }}
          CGP_PRIVATE_KEY_DEV: ${{ secrets.CGP_PRIVATE_KEY_DEV }}

      - name: Git Pull e Docker compose
        run: |
          ssh_user=root
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            ip_address=35.196.116.28
            branch=dev
          else
            ip_address=34.68.95.239
            branch=main
          fi

          ssh -o StrictHostKeyChecking=no -i private-key.pem $ssh_user@$ip_address "
            cd github/biolink
            git pull origin $branch
            docker compose up --build -d
            "

            
